### ISSUE TITLE
大佬，什么时候安排上个人短评

### ISSUE THREAD

**Issue by AkaiNoCat** [Qliangw/notion_sync_data#11]
╰(*°▽°*)╯

**Comment by Qliangw** [comment]
最近没有时间搞（过一段时间安排上

- TODO

- [ ] 个人短评
- [ ] 书籍简介
- [ ] 界面化导入（不再用命令行了，降低上手难度

**Comment by jkhnfk** [comment]
有开发双向同步的可能不？😳😳😳😳

**Comment by Qliangw** [comment]
> 有开发双向同步的可能不？😳😳😳😳

理论可以，模拟手动标记即可（最近没有时间搞，咕咕咕

**Comment by jkhnfk** [comment]
好的好的，加油。期待中。
