### ISSUE TITLE
页数中项中出现了汉字导致程序无法处理

### ISSUE THREAD

**Issue by xxhcu** [Qliangw/notion_sync_data#14]
【RUN】导入异常：invalid literal for int() with base 10: '285页'！
【RUN】捉到Bug了,请您反馈！
豆瓣页面有人提交书目信息时加入了一个‘页’字，导致呈现结果是‘页数：285页’。
感谢大佬的程序，辛苦了，谢谢！
![屏幕截图 2022-06-30 083231](https://user-images.githubusercontent.com/31881823/176568222-c1b164c0-030e-48b6-9a28-b82759671a33.png)

**Comment by Qliangw** [comment]
感谢反馈，后续会解决这个问题（不过现在还没有时间，还要过一两个月后）
