### ISSUE TITLE
notion中标记时间列为空

### ISSUE THREAD

**Issue by brandon0824** [Qliangw/notion_sync_data#15]
感谢大佬的付出！有个疑问 在运行代码之后不管是电影还是书籍 notion里边标记时间那一栏设置property可见但是每一行的值还是为空

**Comment by Qliangw** [comment]
预留的。。。还没有时间去搞（实在抱歉，TODO的功能鸽了这么久）

**Comment by brandon0824** [comment]
没事没事 期待这个新功能哈哈
