### ISSUE TITLE
初始化数据库时报错：网络请求错误:'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by jonathanfan-ee** [Qliangw/notion_sync_data#16]
![image](https://user-images.githubusercontent.com/88966334/181494055-ded8394b-6690-4390-b8cc-f602b564fa8a.png)
如上图，求教。
配置文件检查过应当没有问题，并且已经重试过多次
Windows10，python3.10

**Comment by Qliangw** [comment]
似乎是网络问题，确认一下notion是否能正常打开（我试了一下没有复现该问题）

可以试试修改一下host，可以参考一下这个 [https://jerryw.cn/notion-faster](url)
