### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by jerryc127** [Qliangw/notion_sync_data#21]
初始化
显示都存在了
但是页面还是空白的

![image](https://user-images.githubusercontent.com/16351105/222061946-f894ffe0-e44d-4627-afb5-3d4d5eda76b6.png)

运行了 显示 ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
![image](https://user-images.githubusercontent.com/16351105/222062054-a1f55ae8-3df4-405d-8b71-2d1eb027c306.png)

**Comment by Qliangw** [comment]
最新版已修复
