### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jerryc127** [Qliangw/notion_sync_data#22]
最新版

```
root@myw:~/notion_sync_data# python3 run.py -m movie -s collect
正在加载配置：/root/notion_sync_data/doc/config.yaml
----开始拉取数据----
正在加载配置：/root/notion_sync_data/doc/config.yaml
【Config】读取用户配置的文件[config.yaml]
【Config】- 取得浏览器 user-agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
【Config】- 取得用户 id：iam****yc
【Config】- 取得监控日期：0
【Config】- 取得 notion 的 token：secret_6G7Dup*************************23tdMPcmxd58
【Notion】- 取得notion的database_id：f56bfe12a***************dcea7096
【DouBan】配置用户自定义cookie，重要用户信息已隐藏
【RUN】请求url，获取返回值
【DouBan】访问movie中标记为collect的状态第1页数据完成
【DouBan】- 第1页共有媒体个数：15
【DouBan】- 第1页监控日期内数据个数：15
【DouBan】- 是否继续访问下一页：True
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：1s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：7s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：8s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：10s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：8s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：3s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：3s
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：5s
【RUN】请求url，获取返回值
【RUN】- movie数据信息整理为json格式
【RUN】导入异常：time data '\n' does not match format '%Y-%m-%d'！
【RUN】捉到Bug了,请您反馈！
【RUN】- 访问豆瓣时随机休眠时间1-10s，本次休眠：9s
```

**Comment by Brikarl** [comment]
报错的电影链接可以给一下吗？

**Comment by jerryc127** [comment]
不清楚报错的是哪一个电影

用户是 iamjerryc
你可以爬一下

**Comment by Brikarl** [comment]
> 不清楚报错的是哪一个电影
> 
> 用户是 iamjerryc 你可以爬一下

已发起PR，合并之后辛苦拉一下最新代码试一下。https://github.com/Qliangw/notion_sync_data/pull/24

**Comment by Qliangw** [comment]
已修复

**Comment by jerryc127** [comment]
> 已修复

有其他错误

```
----开始拉取数据----
正在加载配置：/root/notion_sync_data/doc/config.yaml
【Config】读取用户配置的文件[config.yaml]
【Config】- 取得浏览器 user-agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
【Config】- 取得用户 id：iam****yc
【Config】- 取得监控日期：0
【Config】- 取得 notion 的 token：secret_6G7Dup*************************23tdMPcmxd58
【Notion】- 取得notion的database_id：f56bfe12a***************dcea7096
【DouBan】配置用户自定义cookie，重要用户信息已隐藏
【RUN】请求url，获取返回值
【DouBan】访问movie中标记为collect的状态第1页数据完成
【DouBan】- 第1页共有媒体个数：15
【DouBan】- 第1页监控日期内数据个数：15
【DouBan】- 是否继续访问下一页：True
【RUN】请求url，获取返回值
【RUN】解析失败：name 'my_date' is not defined
【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/34795100/
【RUN】请求url，获取返回值
【RUN】解析失败：name 'my_date' is not defined
【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/25966085/
【RUN】请求url，获取返回值
【RUN】解析失败：name 'my_date' is not defined
【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/35311878/
```

你这个问题不是一般的多啊。

**Comment by Qliangw** [comment]
已修复https://github.com/Qliangw/notion_sync_data/blob/main/CHANGELOG.rst

**Comment by Qliangw** [comment]
> > 已修复
> 
> 有其他错误
> 
> ```
> ----开始拉取数据----
> 正在加载配置：/root/notion_sync_data/doc/config.yaml
> 【Config】读取用户配置的文件[config.yaml]
> 【Config】- 取得浏览器 user-agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
> 【Config】- 取得用户 id：iam****yc
> 【Config】- 取得监控日期：0
> 【Config】- 取得 notion 的 token：secret_6G7Dup*************************23tdMPcmxd58
> 【Notion】- 取得notion的database_id：f56bfe12a***************dcea7096
> 【DouBan】配置用户自定义cookie，重要用户信息已隐藏
> 【RUN】请求url，获取返回值
> 【DouBan】访问movie中标记为collect的状态第1页数据完成
> 【DouBan】- 第1页共有媒体个数：15
> 【DouBan】- 第1页监控日期内数据个数：15
> 【DouBan】- 是否继续访问下一页：True
> 【RUN】请求url，获取返回值
> 【RUN】解析失败：name 'my_date' is not defined
> 【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/34795100/
> 【RUN】请求url，获取返回值
> 【RUN】解析失败：name 'my_date' is not defined
> 【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/25966085/
> 【RUN】请求url，获取返回值
> 【RUN】解析失败：name 'my_date' is not defined
> 【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/35311878/
> ```
> 
> 你这个问题不是一般的多啊。

已修复 https://github.com/Qliangw/notion_sync_data/blob/main/CHANGELOG.rst

**Comment by jerryc127** [comment]
> > > 已修复
> > 
> > 
> > 有其他错误
> > ```
> > ----开始拉取数据----
> > 正在加载配置：/root/notion_sync_data/doc/config.yaml
> > 【Config】读取用户配置的文件[config.yaml]
> > 【Config】- 取得浏览器 user-agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
> > 【Config】- 取得用户 id：iam****yc
> > 【Config】- 取得监控日期：0
> > 【Config】- 取得 notion 的 token：secret_6G7Dup*************************23tdMPcmxd58
> > 【Notion】- 取得notion的database_id：f56bfe12a***************dcea7096
> > 【DouBan】配置用户自定义cookie，重要用户信息已隐藏
> > 【RUN】请求url，获取返回值
> > 【DouBan】访问movie中标记为collect的状态第1页数据完成
> > 【DouBan】- 第1页共有媒体个数：15
> > 【DouBan】- 第1页监控日期内数据个数：15
> > 【DouBan】- 是否继续访问下一页：True
> > 【RUN】请求url，获取返回值
> > 【RUN】解析失败：name 'my_date' is not defined
> > 【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/34795100/
> > 【RUN】请求url，获取返回值
> > 【RUN】解析失败：name 'my_date' is not defined
> > 【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/25966085/
> > 【RUN】请求url，获取返回值
> > 【RUN】解析失败：name 'my_date' is not defined
> > 【RUN】- 解析该页面出现问题，媒体链接：https://movie.douban.com/subject/35311878/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你这个问题不是一般的多啊。
> 
> 已修复 https://github.com/Qliangw/notion_sync_data/blob/main/CHANGELOG.rst

root@myw:~/notion_sync_data# python3 run.py -m movie -s all
正在加载配置：/root/notion_sync_data/doc/config.yaml
----开始拉取数据----
【RUN】开始获取movie的do状态信息
正在加载配置：/root/notion_sync_data/doc/config.yaml
【Config】读取用户配置的文件[config.yaml]
【Config】- 取得浏览器 user-agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
【Config】- 取得用户 id：iam****yc
Traceback (most recent call last):
  File "/root/notion_sync_data/run.py", line 70, in <module>
    start_sync(media_type=media, media_status=i)
  File "/root/notion_sync_data/sync_data/app/sync.py", line 261, in start_sync
    monitoring_day = config_dict[ConfigName.DOUBAN.value][ConfigName.DOUBAN_DAY.value] or int(env.get("DOUBAN_DAY"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'


这个又是什么报错

ps. 你上传到 github 时没有测试么
