### ISSUE TITLE
个人评分/片长/评分 为空

### ISSUE THREAD

**Issue by jerryc127** [Qliangw/notion_sync_data#30]
![image](https://user-images.githubusercontent.com/16351105/224753615-7f063858-ff16-4619-9e56-ed25ac418fd1.png)
![image](https://user-images.githubusercontent.com/16351105/224753701-b91e1af5-8924-4a2f-a87b-1f980459d9e4.png)

**Comment by Qliangw** [comment]
个人评分和短评，填写cookies试试看

片长还没做处理，只是预留项
