### ISSUE TITLE
book同步不全，电影、游戏都无问题

### ISSUE THREAD

**Issue by MoHaoNan** [Qliangw/notion_sync_data#36]

**Comment by Qliangw** [comment]
麻烦详细说明

1. 是什么不全，标记了没有同步到notion？还是同步到notion了但有些内容为空
2. 提供截图
3. 提供链接

以上方便我定位问题，谢谢。

**Comment by MoHaoNan** [comment]
![Snipaste_2023-08-04_21-05-19](https://github.com/Qliangw/notion_sync_data/assets/40196984/7b919222-720a-4545-8bdd-b59931d5357c)

**Comment by Qliangw** [comment]
```bash
  # 【必填】 1. 填写为0时，监控所有的  | 2. 填写非零的正整数，则监控x天内的。比如填写30，则监控一个月内的；365，则监控一年内的。
  day:
```

这个参数呢，时间是不是没有覆盖到

**Comment by MoHaoNan** [comment]
已经配置为0了，监控所有。游戏和电影都能成功全部导入

**Comment by Qliangw** [comment]
那剩下的那几本书没有导入的问题，我能想到的可能就是这几本书**没有公开标记**

你可以用浏览器的**无痕模式**去看看，能否看到未导入的图书。
