### ISSUE TITLE
-s all 的时候出错

### ISSUE THREAD

**Issue by donaldxdonald** [Qliangw/notion_sync_data#4]
经排查，是因为获取全部数据即 -s all 的时候， databases.py 中 获取的 body 中的 标记状态.select.name 为空，导致 notion api 报错了

**Comment by Qliangw** [comment]
目前影视的功能还没有做，本来想着暂时不支持all这个功能，既然出现了报错，下个版本我先修复了这个问题。

感谢您的测试

**Comment by Qliangw** [comment]
> 经排查，是因为获取全部数据即 -s all 的时候， databases.py 中 获取的 body 中的 标记状态.select.name 为空，导致 notion api 报错了

已解决
