### ISSUE TITLE
运行命令 `python run.py -f init` 提示配置文件不存在

### ISSUE THREAD

**Issue by lingcongdesu** [Qliangw/notion_sync_data#6]
运行 `python run.py -h` 命令无问题，但运行 `python run.py -f init` 和 `python run.py -m book -s wish` 两条命令时都提示配置文件不存在（但我已经按照使用方法的说明把 doc 文件夹里的 config.yaml.simple 文件复制并重命名为了 config.yaml 😭

**Comment by lingcongdesu** [comment]
系统：macOS 12.1
Python 3.9

**Comment by Qliangw** [comment]
> 运行 `python run.py -h` 命令无问题，但运行 `python run.py -f init` 和 `python run.py -m book -s wish` 两条命令时都提示配置文件不存在（但我已经按照使用方法的说明把 doc 文件夹里的 config.yaml.simple 文件复制并重命名为了 config.yaml 😭

我删除本地配置文件，在liunx端和windows端没有复现出该问题。

提个建议，看能否解决：
1. 重新安装依赖 `pip install -r requirements.txt`
2. 本地的删除再重新获取试试看

**Comment by lingcongdesu** [comment]
> > 运行 `python run.py -h` 命令无问题，但运行 `python run.py -f init` 和 `python run.py -m book -s wish` 两条命令时都提示配置文件不存在（但我已经按照使用方法的说明把 doc 文件夹里的 config.yaml.simple 文件复制并重命名为了 config.yaml 😭
> 
> 我删除本地配置文件，在liunx端和windows端没有复现出该问题。
> 
> 提个建议，看能否解决：
> 
> 1. 重新安装依赖 `pip install -r requirements.txt`
> 2. 本地的删除再重新获取试试看

* 输入 `python3 /Users/apple/notion_sync_data/run.py -h` 可顺利查看帮助文档；
* 在 /Users/apple/notion_sync_data/doc 和 /Users/apple/notion_sync_data 文件夹中都放了一份根据配置参数说明修改的 config.yaml 文件，仍然在运行 `python3 /Users/apple/notion_sync_data/run.py -f init` 命令时提示 `【RUN】配置文件不存在，请复制/doc/config.yaml.simple 到本目录为config.yaml，再重新启动` 🙉 代码小白落泪。

**Comment by Qliangw** [comment]
你试试这样呢

1. `cd /Users/apple/notion_sync_data`
2. `python3 run.py -f init`

**Comment by lingcongdesu** [comment]
----初始化数据库----
【RUN】自动配置文件不存在，将会自动创建auto.yaml文件
【RUN】将个人数据库配置复制到auto.yaml中，将来版本会移除移动配置的功能！
【RUN】读取程序自动配置的文件[auto.yaml]
【RNU】创建book数据库--初始化参数
创建数据库失败，请检查是否页面有授权给【集权】，再重新使用本程序

**Comment by Qliangw** [comment]
看一下 [说明](https://www.notion.so/ptest/notion_sync_data-3d774621eda447c2a1428d2d3b118867)

记得在notion页面点一下share，把获取的token填入。

我刚刚更新了下说明文档，对比图片看一下

**Comment by lingcongdesu** [comment]
感谢！！我发现原来是页面 share 的时候没有把 token 给 invite 进去！！成功了
