### ISSUE TITLE
爬虫中途出现错误

### ISSUE THREAD

**Issue by lingcongdesu** [Qliangw/notion_sync_data#7]
在爬取看过的影视列表的过程中，中途出现了一处错误：

> 【RUN】请求url，获取返回值
> 【RUN】未解析到编剧数据：'编剧' is not in list
> 【RUN】未解析到主演数据：'主演' is not in list
> 【RUN】解析失败：'语言:' is not in list

可能是因为那部电影年代比较早，信息不太全。😂 一旦因为这个错误暂停就没办法继续了。想请教一下出现这种情况后，有没有办法跳过这一部作品继续爬虫呢？

**Comment by Qliangw** [comment]
感谢反馈

能否定位到这个媒体，提供一下媒体链接，针对这一类的我做个跳过处理

**Comment by lingcongdesu** [comment]
https://movie.douban.com/subject/2310158/

大佬辛苦啦！！

**Comment by Qliangw** [comment]
已解决 [更新日志](https://github.com/Qliangw/notion_sync_data/blob/main/CHANGELOG.rst)

`git pull` 拉取一下最新库即可

**Comment by lingcongdesu** [comment]
非常感谢！试了一下可以啦👍🏻
